# progress-planner-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: progress-planner
  name: progress-planner-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: progress-planner
    spec:
      containers:
      - image: gcr.io/progressplanner-199801/progress-planner
        name: progress-planner
        ports:
        - containerPort: 3000
          name: http-server
